spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    hikari:
      username: root
      password: '!Qazsew1234'
      driver-class-name: com.mysql.cj.jdbc.Driver

